# -*- coding: utf-8 -*-
"""backend.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13lxEjYvXySFCAX3KJdyIIT5WMG8hg4D5
"""

from fastapi import FastAPI
from pydantic import BaseModel
from chatbot import get_answer

app = FastAPI()

class QueryRequest(BaseModel):
    question: str

@app.post("/chat")
def chat(request: QueryRequest):
    return {"answer": get_answer(request.question)}