# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P0d1DUyJYqgYhrNAk-P_6lpunv2ZJLdS
"""

from langchain.llms import OpenAI
from langchain.chains import RetrievalQA
from retriever import load_retriever

retriever = load_retriever()
llm = OpenAI()
qa_chain = RetrievalQA(llm=llm, retriever=retriever)

def get_answer(question):
    return qa_chain.run(question)