# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HvWz3tBNAA4hA6ca_oyfJFJBDXjzT2p4
"""

import streamlit as st
from chatbot import get_answer

st.title("Chat with Your AI")
user_input = st.text_input("Ask a question:")
if user_input:
    response = get_answer(user_input)
    st.write("AI Response:", response)