# -*- coding: utf-8 -*-
"""retriever.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1upgLbDS5P6RVJOPHQjcUXl12aFRgCqTn
"""

from langchain.document_loaders import DirectoryLoader
from langchain.embeddings import OpenAIEmbeddings
from langchain.vectorstores import Chroma

def load_retriever():
    loader = DirectoryLoader("documents")  # Ensure 'documents/' contains personal files
    documents = loader.load()

    embedding_model = OpenAIEmbeddings()
    vector_db = Chroma.from_documents(documents, embedding_model)
    return vector_db.as_retriever()